### ISSUE TITLE
JTA folder is not generated after pressing F5?

### ISSUE THREAD

**Issue by test123604** [BobbySolo/JTAMods#12]
Hello, I’m sorry I didn’t find your contact information and contacted you here. I used your script before, but after the system was reinstalled, the JTA folder did not appear by pressing F5. I strictly followed the procedure you wrote. The operation was unsuccessful. Have you ever encountered such a problem? Is there a solution? Thank you

**Comment by fabbrimatteo** [comment]
Hi,
Did you run GTA V using administrator privilege?

**Comment by test123604** [comment]
I log in to the game through steam. I don't know if it's administrator mode

**Comment by fabbrimatteo** [comment]
Does the prompt menu appear after pressing F5?

**Comment by test123604** [comment]
Nothing happens

**Comment by fabbrimatteo** [comment]
Ok so probably you have to recompile the mods. Follow the [Developer Guide](https://github.com/fabbrimatteo/JTA-Mods#developer-guide) and let me know!

**Comment by test123604** [comment]
After the source code is recompiled, the newly generated script file still fails to respond. Check the game log and show that: ASI: loading "E: steamlibrary / steamapps / common / Grand Theft Auto V\ ScenarioCreator.asi "
" ScenarioCreator.asi " failed to load

**Comment by fabbrimatteo** [comment]
Does the NativeTrainer.asi works? You can find that as an example inside the Script Hook V downloaded package (step 3 [here](https://www.dev-c.com/gtav/scripthookv/)).

Also, try re-downloading Script Hook V because they might have updated the library recently to keep up with the GTA patches.

**Comment by test123604** [comment]
The Script Hook V used is the latest version, and NativeTrainer.asi is useful

**Comment by fabbrimatteo** [comment]
You said that you used my mod before, and after reinstalling my mod was not working anymore. Right? What you reinstalled?

**Comment by test123604** [comment]
Nothing, just reinstalled the windows system

**Comment by test123604** [comment]
Does the pure version and professional version of the windows version affect the operation of mods?

**Comment by fabbrimatteo** [comment]
No they should not but you could try on another machine
