### ISSUE TITLE
The mods fails to load but Native trainier is fine

### ISSUE THREAD

**Issue by rao1219** [BobbySolo/JTAMods#14]
Hi, I follow the installation guide but when I press F5 or F8, nothing happens. But the official Native trainer works fine. 

Maybe this version needs to update, could you please have a check?

**Comment by fabbrimatteo** [comment]
Hi, the precompiled asi files are not updated. Try to recompile the mod from scratch following [these](https://github.com/fabbrimatteo/JTA-Mods#developer-guide) steps.
