### ISSUE TITLE
Sample Dataset

### ISSUE THREAD

**Issue by NagabhushanSN95** [BobbySolo/JTAMods#15]
Hi,
Thanks for sharing your work. I'm looking for databases with ground truth depth, camera pose and camera intrinsics. Your database has the latter two and it looks like I can get ground truth depth using 3d points as you described [here](https://github.com/fabbrimatteo/JTA-Mods/issues/3#issuecomment-430304395). 

To verify, it would be helpful if you can provide a sample of the dataset, and if I find it useful for my work, I can write a mail to you requesting the complete database and also buy the GTA V game.

**Comment by fabbrimatteo** [comment]
Hi,
I am sorry, but I can not share GTA V content until you provide the statement reported [here](https://github.com/fabbrimatteo/JTA-Dataset#obtain-the-dataset).

**Comment by NagabhushanSN95** [comment]
Okay, thanks. You're asking me to say that I will purchase GTA V even before I know if it will be useful :)
