### ISSUE TITLE
i installed the latest version of GTA5 as well as the 2017 version, but failed to load asi files.

### ISSUE THREAD

**Issue by kkiritoo** [BobbySolo/JTAMods#19]
// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFA91600000
API: "DirectInput8Create" => 00007FFA91608F80
API: "DllCanUnloadNow" => 00007FFA91619EB0
API: "DllGetClassObject" => 00007FFA91619F80
API: "DllRegisterServer" => 00007FFA91623CB0
API: "DllUnregisterServer" => 00007FFA91623F30
LOADER: Loading *.asi plugins
ASI: Loading "D:\Grand Theft Auto V\DatasetAnnotator.asi"
     "DatasetAnnotator.asi" failed to load
ASI: Loading "D:\Grand Theft Auto V\NativeTrainer.asi"
     "NativeTrainer.asi" => 00007FFA91590000
ASI: Loading "D:\Grand Theft Auto V\ScenarioCreator.asi"
     "ScenarioCreator.asi" failed to load
LOADER: Finished loading *.asi plugins

**Comment by kkiritoo** [comment]
btw, i used a game checkpoint to overpass the first mission
should i complete it myself?

**Comment by kkiritoo** [comment]
btw, i used a game save to overpass the first mission
should i complete it myself?

**Comment by fabbrimatteo** [comment]
Hi, the asi files are outdated. Try following the dev guide https://github.com/fabbrimatteo/JTA-Mods#developer-guide

You should be fine, as long as the first mission does not start each time you start the game!

**Comment by kkiritoo** [comment]
> Hi, the asi files are outdated. Try following the dev guide https://github.com/fabbrimatteo/JTA-Mods#developer-guide
> 
> You should be fine, as long as the first mission does not start each time you start the game!

Thanks a lot! I will take a try
