### ISSUE TITLE
Unable to change shot for the acquisition

### ISSUE THREAD

**Issue by simonecampisi97** [BobbySolo/JTAMods#20]
Good morning, i'm trying to acquire the frames of the generated scenario, and it was acquired but with a shot different from what I need. I didn't get how to decide the camera shot for the acquisition phase, it is possible to do it ?

**Comment by fabbrimatteo** [comment]
Hi! When you finalize the scenario, the current camera position will be the camera position of your scenario. So simply place the camera where you want by moving the player and then save the scenario!

**Comment by simonecampisi97** [comment]
Thank you very much, now is working! 

Moreover is it possible to get also the bounding box of the people ?

**Comment by fabbrimatteo** [comment]
To recover the bounding boxes you can simply take the extreme joints. Calculate the max and min values for each axes and you have it!

**Comment by simonecampisi97** [comment]
Thank you very much!
