### ISSUE TITLE
Joints inside the airport all occluded

### ISSUE THREAD

**Issue by simonecampisi97** [BobbySolo/JTAMods#21]
Good afternoon, i'm acquiring data with the mod and I noticed that in the frames acquired insied the Airport are all marked as "occluded", hence I can't use these points. Do you know the reason of this?

**Comment by fabbrimatteo** [comment]
Hi Simone. Yeah, some locations seems to be bugged. I haven't figured that out yet! Something you can do is to double-check that the camera is not partially "inside a wall".

**Comment by simonecampisi97** [comment]
Yes I check it, but there is the same problem. Thank you!
