### ISSUE TITLE
Can't use the coordinates to get the annotation. 

### ISSUE THREAD

**Issue by reisguilherme** [BobbySolo/JTAMods#24]
Hello sir, I'm using the mods in a project but I don't know what to do with the CSV file and how to use the coordinates to add the annotation to the images, can you help me?  thank you so much!

**Comment by fabbrimatteo** [comment]
If you want to draw the keypoits simply read each line of the CSV and plot the 2D coordinates using opencv: https://stackoverflow.com/questions/49799057/how-to-draw-a-point-in-an-image-using-given-co-ordinate-with-python-opencv

**Comment by reisguilherme** [comment]
Thank you!
