### ISSUE TITLE
When will dataset on your paper be released?

### ISSUE THREAD

**Issue by soulslicer** [BobbySolo/JTAMods#5]
Great work on this software! Are there any plans to release the recorded datasets?

**Comment by FabioLanzi** [comment]
http://imagelab.ing.unimore.it/jta

**Comment by soulslicer** [comment]
What is the process that you used to extract joint 3D position from GTA? Did you run a 2D pose estimator at multiple synthetic camera angles, and then find the 3D joint?

**Comment by FabioLanzi** [comment]
We used the ```ENTITY :: GET_WORLD_POSITION_OF_ENTITY_BONE``` function of [ScriptHook](https://www.dev-c.com/gtav/scripthookv) which directly returns the 3D coordinates of the joint/bone.
