### ISSUE TITLE
I downloaded the game using steam 

### ISSUE THREAD

**Issue by ahmedbhna** [BobbySolo/JTAMods#6]
I followed the instructions :
Finally, I bought the game, downloaded the script hock file, copied all file in the GTA execution file (dinput8.dll, NativeTrainer.asi, scriptHookV.dl), downloaded SDK (what is the idea of SDK ? i created only emty file "scriptHookV.lib" and finished the first mission. When i press f5 there are two options, f1 for start recording, f2 turn on action reply. I recorded many clips using F5 and F1 but actually no one open. i want to ask how to select specific action and how to open those clips and where is the csv file?
i am really sorry for bothering you

**Comment by fabbrimatteo** [comment]
@ahmedbhna, i moved the issue to the correct repo.

You do not need the SDK if you do not plan to modify the mod's code. Creating the empty file scriptHookV.lib is enough.

I think that the mod did not start at all.

Have you deleted the dsound.dll file in the GTA main folder?
Have you copied ScenarioCreator.asi and DatasetAnnotator.asi in the GTA main folder?
By pressing F5 a menu should appear to the left. Can you see it?

**Comment by ahmedbhna** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/16362169/54337749-4a9ef880-4649-11e9-96af-79cb2b8f1f78.png)

**Comment by ahmedbhna** [comment]
All files in the GTA V folder, there is no dsound.dll file installed in the folder. I chanced the permission to read & execute and write.
when i press f4 i got this screen 
![Screenshot from 2019-03-14 11-18-26](https://user-images.githubusercontent.com/16362169/54338392-365bfb00-464b-11e9-935a-215999279c02.png)

This mean that the script hook is fine. When i press F5  there are two options, f1 for start recording, f2 turn on action reply

**Comment by fabbrimatteo** [comment]
Ok seems like my mod didn't start at all. My asi files might be outdated. I will update them soon. 

Anyway, have you tried restarting the game with the asi file already in the folder?

**Comment by ahmedbhna** [comment]
yes i did,
if you don't mind, i want to ask you if you could record 2 fighting video
and the annotation to see how is the fight there.

**Comment by fabbrimatteo** [comment]
Sorry for the delay. Try to download the .asi file again now. I have updated them.

**Comment by ahmedbhna** [comment]
Matteo,
Thank you, i will do that right now.
Thank you so much

**Comment by xiangyuxu0815** [comment]
Hi, I'm having the same problem here.  Pressing F5 and F8 has no response.
Also, is 'Runtime asi script reloading ' necessary if I only have ScenarioCreator.asi and DatasetAnnotator.asi in the main folder? Thanks for your time.

**Comment by fabbrimatteo** [comment]
@ShawnXu10 "Runtime asi script reloading" allows you to load and unload the .asi scripts. It is helpful because you can disable/enable the mods at any time by pressing CTRL + R. It is not necessary, just helpful.

Have you menaged to make NativeTrainer.asi work (by pressing F4)?

**Comment by xiangyuxu0815** [comment]
> @ShawnXu10 "Runtime asi script reloading" allows you to load and unload the .asi scripts. It is helpful because you can disable/enable the mods at any time by pressing CTRL + R. It is not necessary, just helpful.
> 
> Have you menaged to make NativeTrainer.asi work (by pressing F4)?

NativeTrainer.asi works fine. I got the right result when pressing F4.

**Comment by fabbrimatteo** [comment]
Ok seems like my .asi are still outdated. I have to recompile them. I can provide the new files next week.

If you don't want to wait, you can follow the Developer Guide and compile the file by your own!

**Comment by fabbrimatteo** [comment]
We tried the mods in our machines and everything works fine. Maybe for some reasons you do not have the right permissions to the game folder. Try changing the permissions of the GTA V folder (read, write and execute) and let me know if it works!

**Comment by fabbrimatteo** [comment]
I uploaded the new asi files. Now it should work.
