### ISSUE TITLE
Failed to load the mod

### ISSUE THREAD

**Issue by lesterlo** [BobbySolo/JTAMods#9]
I download the DatasetAnnotator.asi and ScenarioCreator.asi and put it to the game folder. But the asiloader said both of the mod failed to load. I have already set the permission of the game folder.

What should I do?

**Comment by fabbrimatteo** [comment]
Hi @lesterlo,
Try to run the game as administrator.

Also, have you menaged to make NativeTrainer.asi work? If yes, I really do not know what could be the problem. A solution that will work for sure is to compile the asi file by yourself, following the [Developer Guide](https://github.com/fabbrimatteo/JTA-Mods#developer-guide).

**Comment by fabbrimatteo** [comment]
I upoaded the new asi files. Now it should work.
